
global RegisterEnum : function(enumName : string)
global RegisterClass : function(className : string)
global GetUProperty : function(obj : any, key : any) : nil | any
global SetUProperty : function(obj : any, key : any)
global LoadObject : function(objName : string) : any
global LoadClass : function(className : string) : any
global NewObject : function(objClass : any, objOuter : any, objName : string, scriptName : string) : any


